### ISSUE TITLE
Forbidden Page on Registration

### ISSUE THREAD

**Issue by ThePlatinum** [virtualmin/virtualmin.com#1]
After filling out the registration form, the page returns a Forbibben Error

![Screenshot from 2024-03-01 19-06-47](https://github.com/virtualmin/virtualmin.com/assets/30179079/c478f421-0054-407b-b560-1abe7f5c5149)

**Comment by iliajie** [comment]
Hello,

This isn't something I can reproduce. Can you try another browser or incognito tab?

What browser are you using?

Did you receive verification email?

**Comment by ThePlatinum** [comment]
I tried another browser now (Chrome), and it works fine but doesn't work on Firefox.

**Comment by iliajie** [comment]
I am sorry but it works for me in Firefox as well. I think it was just a one-time glitch.

**Comment by ThePlatinum** [comment]
Thank you very much for your reply.
