### ISSUE TITLE
Incorrect URL References in Virtualmin Documentation: "How to Create Virtual Servers" Page

### ISSUE THREAD

**Issue by aayubkh** [virtualmin/virtualmin.com#3]
### Description:
Hi Virtualmin Team,

I hope this message finds you well. I have identified some incorrect URL references on the [How to Create Virtual Servers](https://www.virtualmin.com/docs/getting-started/how-to-create-virtual-servers) documentation page. Here are the details:

There are incorrect URL references on the "How to Create Virtual Servers" page in the Virtualmin documentation. These incorrect URLs result in 404s.

1. Top-level servers:
- [Wrong URL](https://www.virtualmin.com/docs/step-by-step-tutorials/understanding-virtual-server-and-account-types/#understanding-top-level-virtual-servers)
- [Correct URL](https://www.virtualmin.com/docs/getting-started/understanding-virtual-server-and-account-types/#understanding-top-level-virtual-servers)
2. Sub-servers:
- [Wrong URL](https://www.virtualmin.com/docs/step-by-step-tutorials/understanding-virtual-server-and-account-types/#understanding-sub-servers)
- [Correct URL](https://www.virtualmin.com/docs/getting-started/understanding-virtual-server-and-account-types/#understanding-sub-servers)
3. Aliases:
- [Wrong URL](https://www.virtualmin.com/docs/step-by-step-tutorials/understanding-virtual-server-and-account-types/#understanding-virtual-server-aliases)
- [Correct URL](https://www.virtualmin.com/docs/getting-started/understanding-virtual-server-and-account-types/#understanding-virtual-server-aliases)

### Steps to Reproduce:
1. Navigate to the [How to Create Virtual Servers](https://www.virtualmin.com/docs/getting-started/how-to-create-virtual-servers) page
2. Click on the links for "Top-level servers", "Sub-servers", and "Aliases".

### Expected Behavior:
The links should direct to the correct sections without resulting in a 404 error.

### Actual Behavior:
The links result in a 404 error due to incorrect URL references.

### Suggested Fix:
Update the URLs on the "How to Create Virtual Servers" page with the correct ones provided above.

Thank you for addressing this issue!

@swelljoe

**Comment by iliajie** [comment]
Thank you very much for reporting this! All has been fixed now!
