### ISSUE TITLE
Pro feature "Edit Web Pages" is not explained

### ISSUE THREAD

**Issue by SamSirry** [virtualmin/virtualmin.com#6]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

![image](https://github.com/user-attachments/assets/a657b6b1-0b93-4bcb-b1d5-b2ff5db841b3)
This link that points to: https://virtualmin.com/professional/#edit_html
does not have an entry on the page at: https://www.virtualmin.com/docs/professional-features

**Comment by iliajie** [comment]
Thank you for the heads up! It's fixed now!
